#!/usr/bin/env bash




java -cp \
    target/tcatebd-1.0-SNAPSHOT.jar:target/lib/ecj-3.12.3.jar:target/lib/hamcrest-core-1.3.jar:target/lib/javax.websocket-api-1.1.jar:target/lib/jsp-api-2.1.jar:target/lib/junit-4.12.jar:target/lib/tomcat-annotations-api-8.5.20.jar:target/lib/tomcat-api-8.5.20.jar:target/lib/tomcat-catalina-8.5.20.jar:target/lib/tomcat-coyote-8.5.20.jar:target/lib/tomcat-el-api-8.5.20.jar:target/lib/tomcat-embed-core-8.5.20.jar:target/lib/tomcat-embed-el-8.5.20.jar:target/lib/tomcat-embed-jasper-8.5.20.jar:target/lib/tomcat-jasper-8.5.20.jar:target/lib/tomcat-jasper-el-8.5.20.jar:target/lib/tomcat-jni-8.5.20.jar:target/lib/tomcat-jsp-api-8.5.20.jar:target/lib/tomcat-juli-8.5.20.jar:target/lib/tomcat-servlet-api-8.5.20.jar:target/lib/tomcat-util-8.5.20.jar:target/lib/tomcat-util-scan-8.5.20.jar:target/lib/tomcat-websocket-8.5.20.jar:target/lib/tomcat-websocket-api-8.5.20.jar \
    org.bibileanu.teste.start.Start

#target/lib/servlet-api-2.5.jar
